Добавляет раздел Доступность
doka-guide/platform pull request #1008
Opened 2022-10-19 12:59 UTC by TatianaFokina

2022-10-19 14:32 UTC, igsekor requested changes
Круто!!!! Так хочется уже по скорее этот раздел у нас! 😇Добавил ещё файл с переменными окружения, чтобы всё собралось на проде и по инструкции 🙃

2022-10-19 14:32 UTC, igsekor commented on src/styles/dark-theme.css
> +  --color-a11y: hsl(162, 95%, 15%);
Ребята, мы кажется использовали везде новый синтаксис... 😇 Но из меня тот ещё специалист по стилям 🤓

2022-10-19 14:32 UTC, igsekor commented on src/styles/dark-theme.css
> +  --color-recipes: hsla(276, 39%, 32%);
```suggestion
  --color-recipes: hsl(276, 39%, 32%);
```

Тут вроде закралась ошибка из прошлого... Я делал 🐥

2022-10-19 16:36 UTC, TatianaFokina commented on src/styles/dark-theme.css
> +  --color-a11y: hsl(162, 95%, 15%);
Да, судя по другим стилям это так. Поменяла.

2022-10-20 11:40 UTC, TatianaFokina commented
Тоже закрою этот ПР и создам новый, так как из своего форка делала.

2022-10-20 11:40 UTC, closed without merging