Улучшает разметку переключателя тем
doka-guide/platform pull request #1095
Opened 2023-01-24 12:10 UTC by TatianaFokina

ПР в рамках #1054.

Заменила `<div>` и `<span>` на `<fieldset>` и `<legend>` соответственно. Благодаря этому с точки зрения скринридеров это теперь группа чекбоксов с общим названием «Тема». И использовала этот хак с визуально скрытым именем и `<span>`, который скрыт от скринридеров, который уже используется для других похожих элементов.

Как грустно, что этот баг с позиционированием `<legend>` не пофиксили всё ещё.

2023-01-26 10:31 UTC, igsekor approved these changes

2023-01-27 08:46 UTC, HellSquirrel requested changes

2023-01-27 08:46 UTC, HellSquirrel commented on src/libs/github-contribution-service/github-contribution-service.js
> +  let authorActions = {}
А это какое-то отношение имеет к фиксу? Давай отребейзим веточку?

2023-01-27 09:08 UTC, HellSquirrel approved these changes

2023-01-27 09:10 UTC, HellSquirrel approved these changes

2023-01-27 09:51 UTC, merged