Чинит оглавление
doka-guide/platform pull request #194
Opened 2021-06-14 09:46 UTC by furtivite

- Удалил подразделы ДОКА и СТАТЬИ из образования коллекций
- Уменьшил количество коллекций
- Создал новые коллекции на место старых
- Убрал задвоенный подвал в шаблоне статей

2021-06-14 09:58 UTC, pepelsbey reviewed
Сейчас все файлы collections/*.njk отличаются только строкой с названием категории. Мне кажется, что это скорее цикл в шаблоне aside.njk, а не 4 инклюда одинаковых файлов.

2021-06-14 09:59 UTC, furtivite commented
> Сейчас все файлы `collections/*.njk` отличаются только названием категории. Мне кажется, что это цикл прямо в шаблоне, а не 4 инклюда идентичных файлв. Упростим?

Да, кажется, это можно было бы упростить больше.

2021-06-14 10:00 UTC, pepelsbey reviewed
…

2021-06-14 11:26 UTC, furtivite commented
Нужна помощь:

есть перебор массива функцией `{% asyncAll %}` и есть макрос, который может подставлять мне то, что он принимает в себя, как если бы это была функция. 

Хотел сделать:

```njk
{% macro list(title) %}

<ul>
  {% for post in collections.${title} %}
    <li><a href="{{ post.url }}">{{ post.data.title }}</a></li>
  {% endfor %}
</ul>

{% endmacro %}
```

Но `{% for post in collections.${title} %}` ломается, а хотелось бы, чтобы туда подставлялось значение переменно. 

@pepelsbey не знаешь можно ли вообще так?

2021-06-14 15:19 UTC, pepelsbey commented
@furtivite можно, но я лучше бы избавился от макроса, там мало кода и он используется только в этом шаблоне.

2021-06-14 20:24 UTC, pepelsbey commented
У меня с нынешним контентом этот ПР не собирается. Также я хотел бы предложить чуть менее запутанный код. Например, вот так подготовиться к сборке оглавления в цикле:

```njk
{% set sections = [{
  title: 'HTML',
  path: 'html'
},{
  title: 'CSS',
  path: 'html'
},{
  title: 'JavaScript',
  path: 'js'
},{
  title: 'Инструменты',
  path: 'tools'
}] %}

{{ sections[0].title }}
{{ sections[0].path }}
```

И пройтись по этому одним циклом.

2021-06-15 07:19 UTC, furtivite commented
> У меня с нынешним контентом этот ПР не собирается. Также я хотел бы предложить чуть менее запутанный код. Например, вот так подготовиться к сборке оглавления в цикле:
> 
> ```
> {% set sections = [{
>   title: 'HTML',
>   path: 'html'
> },{
>   title: 'CSS',
>   path: 'html'
> },{
>   title: 'JavaScript',
>   path: 'js'
> },{
>   title: 'Инструменты',
>   path: 'tools'
> }] %}
> 
> {{ sections[0].title }}
> {{ sections[0].path }}
> ```
> 
> И пройтись по этому одним циклом.

За заголовки, спасибо, действительно упрощает. 

В цикл типа `{% for post in collections.tools %}...{% endfor %}` я не могу подставить какую-то переменную из массива (например как `{% for post in {{ sections[0].path }} %}`), потому что как только движок видит внутри себя фигурные скобки, сборка ломается.

Я запулил все изменения в контенте на текущий момент. Кажется, сейчас оглавление собирается корректно.
![Снимок экрана 2021-06-15 в 10 14 09](https://user-images.githubusercontent.com/50330458/122009772-159f2480-cdc3-11eb-922c-cbeebb36a92e.png)
![Снимок экрана 2021-06-15 в 10 14 27](https://user-images.githubusercontent.com/50330458/122009788-19cb4200-cdc3-11eb-8252-126ae11a388a.png)

2021-06-15 09:46 UTC, pepelsbey commented
См. кокументацию [Nunjucks: for](https://mozilla.github.io/nunjucks/templating.html#for):

```njk
{% for post in sections }}
  {{ post[loop.index0].title }}
{% endfor %}
```

2021-06-17 19:00 UTC, igsekor requested changes
Стало чище, чем в начале.

2021-06-17 19:00 UTC, igsekor commented on src/includes/collections.njk
> +  {% endif %}
Кажется, что эту секцию можно было бы выделить в отдельную секцию или  в `shortCode` 😇 Она дальше повторяется много раз.

2021-06-17 19:02 UTC, furtivite commented on src/includes/collections.njk
> +  {% endif %}
@igsekor проблема в том, что там используется `collections.html`, и у меня не получилось брать название коллекции как переменную и идти по списку, который есть в начале документа где `html` заменится на некий ${item}, иначе сборка ломается.

2021-06-17 19:39 UTC, igsekor commented on src/includes/collections.njk
> +  {% endif %}
@furtivite можно попробовать что-то типа:

```JavaScript
{% for type in ['css', 'js', 'html', 'tools' ] %}
 {% if section.path == type %}
   <ul>
     {% for post in collections[type] %}
       <li><a href="{{ post.url }}">{{ post.data.title }}</a></li>
     {% endfor %}
   </ul>
   {% endif %}
{% endfor %}
```

2021-06-17 21:27 UTC, nlopin commented on src/includes/collections.njk
> +{% set sections = [{
можем ли мы вынести эти данные куда-то вне шаблона? кажется названия разделов потребуются в других местах тоже и не хотелось бы их дублировать

2021-06-17 21:34 UTC, nlopin commented on src/includes/collections.njk
> +{% for section in sections %}
Есть ли смысл итерироваться по секциям, если в итоге для каждой из них заголовлен свой `if` (25,33, 41, 49 строки)? 

Мне кажется, что маленькие и конкретные файлы лучше, чем файл с большим количеством логики

2021-06-17 21:37 UTC, nlopin commented on src/includes/collections.njk
> +  {% if page.url !== '/all/'%}<details><summary>{% endif %}
Можно подойти к проблеме выбора тегов иначе. Описать страницу объектом, который будет содержать теги для страницы. 

```
const allArticlesPage = {
  wrappedByTag: 'details',
  titleTag: 'summary'
}


const sectionPage = {
  wrappedByTag: '',
  titleTag: 'h2'
}
```

А дальше в шаблоне просто забирать тег. Если это не пройдет, то можно хранить пару открывающий и закрывающий тег

2021-06-17 21:43 UTC, igsekor commented on src/includes/collections.njk
> +{% set sections = [{
У нас же есть такой

2021-06-18 08:21 UTC, pepelsbey requested changes

2021-06-18 08:21 UTC, pepelsbey commented on src/includes/collections.njk
> +  {{section.title}}
```suggestion
  {{ section.title }}
```

2021-06-18 08:21 UTC, pepelsbey commented on src/includes/collections.njk
> +  {% if page.url === '/all/'%}</h2>{% endif %}
```suggestion
  {% if page.url !== '/all/'%}
    </summary>
  {% else %}
    </h2>
  {% endif %}
```

И аналогично выше. Одно же условие и два варианта.

2021-06-18 08:48 UTC, furtivite commented on src/includes/collections.njk
> +{% set sections = [{
Кажется, можно прокидывать оттуда значения, но надо будет добавить `{% if %}`, которые выведут альтернативное название для JS и TOOLS

2021-06-18 11:27 UTC, furtivite commented
@pepelsbey @nlopin @igsekor предлагается сливать так, если нет дополнительных улучшений, а перенести переменные из начала файла в глобальное место можно отдельной итерацией по улучшению.

2021-06-18 11:51 UTC, monochromer commented on src/includes/collections.njk
> +{% set sections = [{
Плюсую за то, чтобы перенести данные секций в папку `data`. Думаю, там им самое место.

2021-06-18 11:53 UTC, igsekor approved these changes
Кажется, стало ещё лучше)

2021-06-18 12:06 UTC, pepelsbey approved these changes

2021-06-19 06:19 UTC, nlopin approved these changes

2021-06-21 07:31 UTC, merged