Добавляет переменную для обозначения последнего редактирования статьи
doka-guide/platform pull request #203
Opened 2021-06-17 18:10 UTC by furtivite

- Добавляет шорткод, который показывает, как давно отредактирована статья.

2021-06-17 18:32 UTC, furtivite commented on .eleventy.js
> +      if (counter >= 5) {
Кажется, в этом моменте можно лучше: потому что есть 42 дня, и 31 день. Надо брать последнюю цифру и плясать от неё

2021-06-17 19:13 UTC, igsekor requested changes

2021-06-17 19:13 UTC, igsekor commented on .eleventy.js
> +      }
Хорошо бы вынести в отдельную функцию, чтобы переиспользовать:

```JavaScript
function prepareString(gap, limit, manyPieces, fewPieces, singlePiece) {
  const c = Math.round(gap / limit)
  if (c >= 5 || (c.length - 1) >= 5) {
    p = manyPieces
  } else if (c >= 2 || (c.length - 1) >= 2) {
    p = fewPieces
  } else {
    p = singlePiece
  }
  return p
}
```

И применять её так:

```JavaScript
piece = prepareString(counter, 86400, 'дней', 'дня', 'день')
```

2021-06-17 21:30 UTC, pepelsbey commented
Ребят, ну Node 14 и 2021 год на дворе :) [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat)

```
const rtf = new Intl.RelativeTimeFormat("ru", {
    localeMatcher: "best fit",
    numeric: "always",
    style: "long",
});

console.log(rtf.format(-1, "day"));
// 1 день назад
console.log(rtf.format(1, "day"));
// через 1 день
```

2021-06-18 11:50 UTC, furtivite commented
@pepelsbey @nlopin @igsekor, кажется, можно смотреть

2021-06-18 11:57 UTC, pepelsbey approved these changes
У меня есть чувство, что длинный if…else можно как-то избежать, но я не уверен сходу как именно. В остальном — норм.

2021-06-18 13:22 UTC, igsekor approved these changes

2021-06-18 13:22 UTC, igsekor commented on .eleventy.js
> +    }
Может цикл?

2021-06-18 13:24 UTC, pepelsbey commented on .eleventy.js
> +    }
Как минимум, `switch…case` :)

2021-06-19 06:30 UTC, nlopin commented on .eleventy.js
> +    }
Если только так:
```
switch(true) {
  case counter > ...
}
```

2021-06-19 06:34 UTC, nlopin approved these changes
Предложил альтернативу со switch, но это опционально

2021-06-21 07:25 UTC, merged