Выводит всех людей, причастных к статье
doka-guide/platform pull request #268
Opened 2021-07-15 13:50 UTC by monochromer

Fix: #267

2021-07-15 14:17 UTC, pepelsbey requested changes
Придираюсь :)

2021-07-15 14:17 UTC, pepelsbey commented on src/includes/contributors.njk
> +      <span>{{ name }}</span>
```suggestion
    <span>{{ name }}</span>
```

2021-07-18 09:22 UTC, igsekor reviewed
@monochromer а стоит ли указывать имя параметра со значением при вызове функции?

2021-07-18 09:46 UTC, monochromer commented
> @monochromer а стоит ли указывать имя параметра со значением при вызове функции?

Если ты про Nunjucks-макрос, то это необязательно, но очень удобно, так как позволяет не запоминать порядок аргументов плюс есть некоторая аналогия с html-атрибутами - ключ-значение.

2021-07-18 11:39 UTC, furtivite approved these changes

2021-07-19 09:43 UTC, pepelsbey approved these changes

2021-07-22 07:35 UTC, merged