Редизайн
doka-guide/platform pull request #275
Opened 2021-07-22 12:13 UTC by monochromer

2021-07-26 08:32 UTC, monochromer commented
https://user-images.githubusercontent.com/6412192/126958795-16ce2395-07a7-4079-a570-91e51808baa0.mp4

2021-07-26 08:45 UTC, furtivite requested changes
<img width="1314" alt="Снимок экрана 2021-07-26 в 11 42 30" src="https://user-images.githubusercontent.com/50330458/126960549-d511a589-e5cd-4e34-b14b-adca786add92.png">

@monochromer, привет! В сборке, не подключились стили, темы не переключаются, но при клике на иконки солнца и луны, срабатывает тогглер.

2021-07-26 09:02 UTC, monochromer commented
> @monochromer, привет! В сборке, не подключились стили, темы не переключаются, но при клике на иконки солнца и луны, срабатывает тогглер.

По какой причине?

2021-07-26 09:05 UTC, furtivite commented
> > @monochromer, привет! В сборке, не подключились стили, темы не переключаются, но при клике на иконки солнца и луны, срабатывает тогглер.
> 
> По какой причине? Может быть, просто кэш.

Да, скорее всего кэш. Я склонировал заново, всё работает. Спасибо.

2021-07-26 09:08 UTC, furtivite requested changes
Всё работает.

2021-07-26 09:08 UTC, furtivite commented on src/scripts/modules/theme-toggle.js
> +  return window.matchMedia(PREFERS_MQ).media !== 'not all';
```suggestion
  return window.matchMedia(PREFERS_MQ).media !== 'not all'
```

2021-07-26 09:10 UTC, furtivite approved these changes

2021-07-27 12:35 UTC, pepelsbey commented
Сейчас кнопка сделана чекбоксом и это скорее хак, чем подходящее решение. Я бы сделал это [кнопкой-тоглером](https://web-standards.ru/articles/theme-switcher/), как в статье.

2021-07-27 12:40 UTC, pepelsbey requested changes
Сейчас кнопка сделана чекбоксом и это скорее хак, чем подходящее решение.
Я бы сделал это [кнопкой-тоглером](https://web-standards.ru/articles/theme-switcher/), как в статье.

```html
<button aria-pressed="false">
  тёмная тема:
  <span aria-hidden="true">выключить</span>
</button>
```

Также стоит поменять сам принцип: если включена тёмная тема, то она должна применяться сразу, как и светлая тема. То есть кнопка нужна только для того, чтобы поменять тему вручную, а базовый принцип должен опираться на дефолты браузера. Это поможет, к примеру, менять тему сайта с помощью системной настройки — сейчас этот не работает.

Я вижу реализацию примерно так:

1. Подключаются базовые стили
2. Подключается файл с переменными для светлой темы (с медиа — лайт)
3. Подключается файл с переменными для тёмной темы (с медиа — дарк)

И браузер уже сам выбирает какую тему применить. А когда это решил сделать пользователь — скрип модифицирует подключение и форсит одну из них.

2021-07-27 12:48 UTC, pepelsbey commented
Статьи по теме:

- [Prefers-color-scheme: Hello darkness, my old friend](https://web.dev/prefers-color-scheme/)
- [Building a color scheme](https://web.dev/building-a-color-scheme/)
- [Improved dark mode default styling with the color-scheme CSS property and the corresponding meta tag](https://web.dev/color-scheme/)

2021-07-27 13:10 UTC, monochromer commented
Насчёт кнопки - согласен.

Разделение на отдельные файлы для светлой и тёмной неудобно, так как они реализуются в виде модификаторов одного блока.

Принцип работы сейчас такой: изначально, исходя из предпочтений пользователя, выбирается тема - светлая или темная. Если браузер не поддерживает соответствующую media query, то выбирается светлая тема. Затем, если пользователь нажимает на кнопку, то выбирается соответствующая тема и сохраняется в _localStorage_. Это выбор идет в приоритете, игнорируя настройки ОС.

2021-07-27 13:25 UTC, pepelsbey commented
> Разделение на отдельные файлы для светлой и тёмной неудобно, так как они реализуются в виде модификаторов одного блока.

Я думал, что мы будем не хардкодить модификаторы, а использовать кастомные свойства для такого. Их как раз можно легко переключать браузерными механизмами. Может пересмотрим решение и будем меньше писать руками? По сути сейчас твой скрипт делает при загрузке то, что браузер уже умеет делать и делает хорошо.

Я бы также подумал про sessionStorage, чтобы после закрытия вкладки мы снова фолбэчились на системную настройку. Но это так, мысли по ходу — можно почитать про опыт больших компаний, посмотреть на их реализации и уже подтюнить.

2021-07-27 13:29 UTC, pepelsbey commented
В общем, если выбираеть между БЭМ-пуризмом (хотя там наследование модификатора, хех) и кастомными свойствами — я бы выбрал второе и позволил браузеру выбирать подходящие стили.

2021-07-27 13:41 UTC, monochromer commented
Получается дублирование - должен быть CSS-класс условно `dark-theme` (чтобы js'ом переключать) и media-выражение:
```css
.dark-theme {
  --color: #fff;
}

@media (prefers-color-scheme: dark) {
  :root {
    --color: #fff;
  }
}
```

2021-07-27 13:44 UTC, monochromer commented
Если нужно закладываться на поддержку с отключенным js, то это нужно обговорить сразу.

2021-07-27 13:48 UTC, pepelsbey commented
> Если нужно закладываться на поддержку с отключенным js, то это нужно обговорить сразу.

Речь не о том, чтобы закладываться на отключенный JS, а потом, чтобы не ставить JS на критическом пути загрузки стилей. Даже если в тёмном браузере мелькнёт светлая тема (или наоборот) — это уже плохо. Только браузер сможет сразу загрузить нужные стили мгновенно их применить.

2021-07-27 14:01 UTC, monochromer commented
Скрипты, как стили, можно внедрить в страницу. Их не так много, чтобы существенно оказывать на размер html.

2021-07-27 19:27 UTC, pepelsbey commented
> Скрипты, как стили, можно внедрить в страницу. Их не так много, чтобы существенно оказывать на размер html.

Так а зачем трюковать, если можно сделать через кастомные свойства без трюков? Неужели так хочется остаться в понятиях БЭМа и переключать классы? Хочется как-то современнее, что ли. Раз уж в браузеры встроили такую возможность и мы можем позволить себе не сильно думать про старые браузеры из-за характера проекта.

2021-07-27 19:57 UTC, monochromer commented
> Так а зачем трюковать, если можно сделать через кастомные свойства без трюков? Неужели так хочется остаться в понятиях БЭМа и переключать классы? Хочется как-то современнее, что ли. Раз уж в браузеры встроили такую возможность и мы можем позволить себе не сильно думать про старые браузеры из-за характера проекта.

Так там и так кастомные свойства, но подход позволяет добавить почти бесплатно 3-ую, 4-ую и т.д. тему оформления, то есть легко масштабируется; позволяет использовать темы одновременно, например, покрасить сайт темной темой, а демку - светлой.

2021-07-27 21:18 UTC, pepelsbey commented
> позволяет добавить почти бесплатно 3-ую, 4-ую и т.д. тему оформления
> позволяет использовать темы одновременно, например, покрасить сайт темной темой, а демку - светлой.

У нас задача проще: есть всего две темы. Демки у нас в отдельных фреймах и скорее всего будут краситься сами, без стилей платформы. Так что я бы не пытался внедрить масштабируемое решение для простой задачи. Чем ближе мы будем к платформе и меньше будет сложностей, тем лучше для опенсорсного проекта.

Правда, давай напишем простую систему для светлой и тёмной темы, которую можно будет показывать как отличное решение тех, кому нужны просто светлая и тёмная тема, как и нам.

2021-07-29 08:03 UTC, monochromer commented
Сделал рефакторинг

2021-07-29 12:43 UTC, monochromer commented
Добавил переключение тем без использования CSS-классов путём блокировки тегов `style`, в которые загружены стили.

Смущает момент, что при переключении тем c помощью кнопки js'ом приходится на теге с тёмной темой делать `style.media = 'all'`, чтобы они применялись всегда независимо от настроек ОС.

2021-07-30 11:09 UTC, monochromer commented
Изменил подключение через `<link>`. Для него (в отличие от `<style>`), атрибут `disabled` является нестандартным  и не работает в Chrome, поэтому отключение сделал через `media='none'`.

2021-07-30 11:27 UTC, pepelsbey commented on src/styles/blocks/link.css
> +}
Ой, а может не будем глобальные стили писать вообще? Ну, кроме блочной модели. Кажется это слишком смелый дефолт, который придётся некрасиво переопределять там, где он не нужен.

2021-07-30 11:31 UTC, monochromer commented on src/styles/blocks/link.css
> +}
Это временно, иначе большинство ссылок "вырви глаз" - синие на чёрном

2021-08-06 14:27 UTC, igsekor approved these changes
Сойдёт и так, но хотелось бы принести потом трёхпозиционный переключатель

2021-08-08 21:15 UTC, nlopin commented on src/scripts/modules/theme-toggle.js
> +    case (!isPrefersColorSchemeSupported()):
нам точно нужны эти кейсы? или тут неявно важную роль играет порядок кейсов, чтобы не дойти до строки 38?

Если так, то может стоит в явном виде хранить эту информацию? Как альтернатива — иметь массив с кортежами `[условие, тема]` и пробегать по ним с помощью того же `find`:

```js
const themeByCriteria = [
  [() => !isPrefersColorSchemeSupported(), DEFAULT_THEME],
  [() => window.matchMedia(PREFERS_MQ_DEFAULT).matches, DEFAULT_THEME],
  [() => window.matchMedia(PREFERS_MQ_DARK).matches, THEMES.DARK],
  [() => true, DEFAULT_THEME],
]

const [,theme] = themeByCriteria.find(([criteria]) => criteria())
return theme
```

Выглядит сложнее, но тут в явном виде виден приоритет

2021-08-08 21:17 UTC, nlopin approved these changes

2021-08-09 10:59 UTC, monochromer commented on src/scripts/modules/theme-toggle.js
> +    case (!isPrefersColorSchemeSupported()):
Порядок важен. Вариант с массивом выглядит функциональненько. Я бы взял его.

2021-08-09 11:25 UTC, monochromer commented on src/scripts/modules/theme-toggle.js
> +    case (!isPrefersColorSchemeSupported()):
Может, значение из storage загнать сюда?
```javascript
function getCurrentTheme() {
  const storedTheme = store.getItem(STORAGE_KEY)

  const themeByCriteria = [
    [() => !!storedTheme, storedTheme],
    [() => !isPrefersColorSchemeSupported(), DEFAULT_THEME],
    [() => window.matchMedia(PREFERS_MQ_DEFAULT).matches, DEFAULT_THEME],
    [() => window.matchMedia(PREFERS_MQ_DARK).matches, THEMES.DARK],
    [() => true, DEFAULT_THEME],
  ]

  const [,theme] = themeByCriteria.find(([criteria]) => criteria())
  return theme

```

2021-08-10 10:38 UTC, pepelsbey approved these changes

2021-08-13 09:04 UTC, closed without merging