Добавляет якоря для мнений авторов
doka-guide/platform pull request #279
Opened 2021-07-27 07:19 UTC by furtivite

В блоке «В работе» у мнений авторов не было ссылок-якорей. Этот PR:
- Добавляет якоря для каждого мнения
- Добавляет быстрые ссылки для каждого мнения
- Якоря уникальны
- Якоря содержат уникальный для статьи `aria-label`

2021-07-27 08:01 UTC, monochromer approved these changes

2021-07-27 08:01 UTC, monochromer commented on src/includes/practices.njk
> +      <article id="practices__{{ practice.fileSlug }}">
Семантически неправильно помещать подобные блоки внутрь `article`, так как они не имеют смысла вне контекста всей статьи

2021-07-27 08:07 UTC, furtivite commented on src/includes/practices.njk
> +      <article id="practices__{{ practice.fileSlug }}">
> Семантически неправильно помещать подобные блоки внутрь `article`, так как они не имеют смысла вне контекста всей статьи

Пожалуй, да, заменил на `<section>`

2021-07-27 13:36 UTC, pepelsbey commented on src/includes/practices.njk
> +      <article id="practices__{{ practice.fileSlug }}">
@monochromer в спецификации есть примеры, в которых с помощью `<article>` размечены комментарии в блоге. То есть в контексте статьи наши советы — это те же комментарии. Я бы не стал тратить на это слишком много времени, но мне кажется, что всё было уместно и нормально и секции не делят какой-то контент на части. Уж лучше дивы с заголовками, в самом деле.

2021-07-27 14:21 UTC, furtivite commented on src/includes/practices.njk
> +      <article id="practices__{{ practice.fileSlug }}">
@pepelsbey в итоге как решили?)

2021-07-27 15:38 UTC, monochromer commented on src/includes/practices.njk
> +      <article id="practices__{{ practice.fileSlug }}">
Пример-то есть, но вот если бы заголовком был не никнейм автора, а, например, "Совет от @user по использованию <tag>", тогда бы он был независимым

2021-07-27 19:29 UTC, pepelsbey commented on src/includes/practices.njk
> +      <article id="practices__{{ practice.fileSlug }}">
Коммент — это не часть чего-то (секция), коммент это всё-таки единица контента, про её независимость можно спорить :) @furtivite давай всё же вернём изначальный артикл.

2021-07-28 09:25 UTC, pepelsbey requested changes
Мне кажется, что собирать схему block__element для ID это плохая затея. Это добавляет шум, как будто в шаблоне появились новые элементы блока. Но это не так, это просто айдишники. Плюс они потом попадают в адреса и ссылки, а значит будет

doka.guide/html/doctype/#practices__something

Что нарушает нашу договорённость в адресах писать через дефисы и ненужно удлинняет адрес. Лучше и привычнее так:

doka.guide/html/doctype/#practices-something

2021-07-28 09:28 UTC, furtivite commented
> Мне кажется, что собирать схему block__element для ID это плохая затея. Это добавляет шум, как будто в шаблоне появились новые элементы блока. Но это не так, это просто айдишники. Плюс они потом попадают в адреса и ссылки, а значит будет
> 
> doka.guide/html/doctype/#practices__something
> 
> Что нарушает нашу договорённость в адресах писать через дефисы и ненужно удлинняет адрес. Лучше и привычнее так:
> 
> doka.guide/html/doctype/#practices-something

@pepelsbey, в принципе, без разницы, я просто сделал вариант, при котором заголовок из практики не будет гарантированно повторяться с заголовком из текста статьи, если там окажется одинаковое значение. Сейчас поправлю.

2021-07-28 10:34 UTC, pepelsbey approved these changes

2021-07-28 10:40 UTC, merged