Вёрстка страницы с индексом
doka-guide/platform pull request #306
Opened 2021-08-30 12:49 UTC by monochromer

2021-08-30 13:05 UTC, monochromer commented on src/styles/blocks/index-block.css
> +@media not all and (min-width: 1366px) {
Аналог `< 1366`

2021-08-30 13:06 UTC, monochromer commented on src/views/article-index.njk
> +    {# fieldset и legend не работают с flexbox/grid #}
Нет, не работает )

2021-08-30 13:13 UTC, pepelsbey commented on src/styles/blocks/index-block.css
> +@media not all and (min-width: 1366px) {
Криптоватая запись, как по мне

2021-08-30 14:50 UTC, nlopin commented on src/views/article-index.11tydata.js
> +      return categoryArticles?.reduce?.((map, article) => {
Мы тут потенциально можем выплюнуть `undefined`, что сломает тот же `sort`  в 70-й строке.

Не уверен, что такое вообще может произойти. Может поправить расчёт `categoryArticles` и возвращать пустой массив если категория пустая? тогда и вопросительные знаки можно будет убрать

2021-08-30 15:22 UTC, monochromer commented on src/views/article-index.11tydata.js
> +      return categoryArticles?.reduce?.((map, article) => {
Там особенность eleventy - все функции из `eleventyComputed` вызываются дважды. На первом вызове собираются зависимости и всегда возвращается `''`.

2021-08-30 21:57 UTC, pepelsbey commented on src/styles/fonts.css
> +  src: url('/fonts/spot-mono/SpotMono-Light.woff2') format('woff2');
Предлагаю использовать для всех файлов один и тот же нейминг, то есть `spot-mono-light`, в этом случае. Ну и с другими шрифтами поправить. Кстати, в случае со Spot Mono, можно обойтись без папки, он у нас один всего :)

2021-08-31 08:45 UTC, pepelsbey approved these changes

2021-08-31 08:53 UTC, furtivite requested changes

2021-08-31 08:53 UTC, furtivite commented on src/styles/blocks/switch.css
> +.switch__input:checked + .switch__label {
Стоит немного подтюнить поведение активного элемента при увеличении масштабирования (Google Chrome 92.0.4515.159). 

100%
![Снимок экрана 2021-08-31 114754](https://user-images.githubusercontent.com/50330458/131472657-e2dc7331-82c7-4019-8571-f83a61649604.png)

110%
![Снимок экрана 2021-08-31 114815](https://user-images.githubusercontent.com/50330458/131472661-fcb86d72-78d1-4645-bf26-51d4fcd75fe2.png)

150%
![Снимок экрана 2021-08-31 114837](https://user-images.githubusercontent.com/50330458/131472664-42b8fa82-3839-4ccd-9b2c-b59a6a1859b3.png)

2021-08-31 08:55 UTC, pepelsbey commented on src/styles/blocks/switch.css
> +.switch__input:checked + .switch__label {
Для тюнинга я бы лучше завёл ишью, чтобы не блокировать ПР

2021-08-31 08:57 UTC, furtivite commented on src/styles/blocks/switch.css
> +.switch__input:checked + .switch__label {
Окей, давай так и сделаю.

2021-08-31 09:00 UTC, pepelsbey commented on src/views/article-index.11tydata.js
> +      return categoryArticles?.reduce?.((map, article) => {
@nlopin резолвим?

2021-08-31 09:24 UTC, nlopin approved these changes

2021-08-31 10:29 UTC, monochromer commented on src/styles/blocks/switch.css
> +.switch__input:checked + .switch__label {
Если нет других замечаний, то нужно явно делать approve, а не просто resolve дискуссии, иначе github не даёт мержить

2021-08-31 11:00 UTC, furtivite approved these changes

2021-08-31 11:00 UTC, merged