Вывод результатов поиска
doka-guide/platform pull request #316
Opened 2021-09-02 06:16 UTC by monochromer

2021-09-02 12:54 UTC, pepelsbey approved these changes

2021-09-02 12:59 UTC, furtivite approved these changes

2021-09-02 13:02 UTC, igsekor requested changes
Локально сайт собирается и работает. Но вот удалённо как-то не выходит. Вот что выводит консоль:

<img width="741" alt="Screenshot 2021-09-02 at 16 01 25" src="https://user-images.githubusercontent.com/13916521/131848269-54836eb7-1603-4ad8-b0b4-e9be72f3991f.png">

2021-09-02 19:01 UTC, igsekor requested changes

2021-09-02 20:10 UTC, nlopin commented on src/scripts/modules/search.js
> +const MIN_SEARCH_SYMBOLS = 3
Согласен. Иначе кучу всего не найдут:

* a
* p
* i
* br
* hr
* tr
* td

2021-09-02 20:13 UTC, nlopin commented on src/scripts/modules/search.js
> +function adjustTextMatch(text, index, query, limit) {
тут нужны комментарии, дающие контекст или читаемые переменные. Иначе через месяц мы уже не разберёмся, что тут происходит

2021-09-02 20:16 UTC, nlopin commented on src/scripts/modules/search.js
> +},
тут кажется так
```suggestion
    },
```

2021-09-02 20:19 UTC, nlopin commented on src/scripts/modules/search.js
> +        .then(function(searchObject) {
давай добавим `catch`, алголия может коряво ответить или умереть. Не хочется умереть вслед за ней. Наверное нужно сообщить об ошибке поиска пользователю

2021-09-02 20:21 UTC, nlopin commented on src/scripts/modules/search.js
> +import algoliasearch from '/algoliasearch/dist/algoliasearch-lite.esm.browser.js'
У меня сложилось ощущение, что мы словарь проекта подстроили под словарь алголии. Не зная этого словаря код сложно читать. Facet, Hit — мы точно хотим использовать эти термины в нашем коде?

2021-09-02 20:22 UTC, nlopin commented on src/scripts/modules/search.js
> +const API_KEY = '8c308ac7e0a1271a2bb0d7836f3703d4'
Этот ключ имеет права только на чтение @igsekor?

2021-09-03 09:14 UTC, nlopin commented on src/scripts/modules/search.js
> +const MIN_SEARCH_SYMBOLS = 3
Есть идея оставить ограничение, но ввести специальный словарь с короткими словами. Обсудим это отдельно, так что это не блокер пул реквеста

2021-09-03 09:17 UTC, furtivite commented on src/scripts/modules/search.js
> +const API_KEY = '8c308ac7e0a1271a2bb0d7836f3703d4'
А мы его в секрет положить не хотим?

2021-09-03 09:39 UTC, igsekor commented on src/scripts/modules/search.js
> +const API_KEY = '8c308ac7e0a1271a2bb0d7836f3703d4'
> Этот ключ имеет права только на чтение @igsekor?

Этот ключ служит только для чтения результатов и самой Algolia рекомендуется для использования в коде.

2021-09-03 09:40 UTC, igsekor commented on src/scripts/modules/search.js
> +const API_KEY = '8c308ac7e0a1271a2bb0d7836f3703d4'
> А мы его в секрет положить не хотим?

В секрет смысла класть нет, он всё равно будет виден в коде на сайте.

2021-09-03 09:42 UTC, igsekor commented on src/scripts/modules/search.js
> +import algoliasearch from '/algoliasearch/dist/algoliasearch-lite.esm.browser.js'
> У меня сложилось ощущение, что мы словарь проекта подстроили под словарь алголии. Не зная этого словаря код сложно читать. Facet, Hit — мы точно хотим использовать эти термины в нашем коде?

Можно и не использовать. Но `results` показалось заезженно. У меня сначала стояли `result` и `filter`. Что думаешь?

2021-09-03 09:44 UTC, igsekor commented on src/scripts/modules/search.js
> +function adjustTextMatch(text, index, query, limit) {
Предлагаю отрефакторить код: рездлить по функционалу на несколько API, добавить комментарии и нормальные имена переменных и функций. Приду с PR.

2021-09-03 21:09 UTC, nlopin commented on src/scripts/modules/search.js
> +import algoliasearch from '/algoliasearch/dist/algoliasearch-lite.esm.browser.js'
меня главным образом facet напрягает. Hit вроде понятно в контексте поиска, если тебе оно кажется лучше, чем result, то я не против её оставить

2021-09-03 21:10 UTC, nlopin commented on src/scripts/modules/search.js
> +const API_KEY = '8c308ac7e0a1271a2bb0d7836f3703d4'
Если он только на чтение, то вопросов нет 👍

2021-09-04 07:13 UTC, igsekor commented on src/scripts/modules/search.js
> +import algoliasearch from '/algoliasearch/dist/algoliasearch-lite.esm.browser.js'
Хорошо, во время рефакторинг учту :)

2021-09-09 06:56 UTC, furtivite requested changes
![Снимок экрана 2021-09-09 095523](https://user-images.githubusercontent.com/50330458/132637579-0c1520ea-8c79-4ebe-9c90-4036503d517d.png)

Кажется, не хватает отступа перед названием категории у первого элемента.

2021-09-09 07:03 UTC, monochromer commented
> Кажется, не хватает отступа перед названием категории у первого элемента.

![image](https://user-images.githubusercontent.com/6412192/132638586-419fe0c0-d483-4243-8aed-251b9a4f97cd.png)

2021-09-09 07:13 UTC, furtivite commented
> > Кажется, не хватает отступа перед названием категории у первого элемента.
> 
> ![image](https://user-images.githubusercontent.com/6412192/132638586-419fe0c0-d483-4243-8aed-251b9a4f97cd.png)

Можно заодно поправить в "выпадашке" в "шапке" (на главной и в статьях)? На отдельной странице - всё хорошо, ты прав.

2021-09-10 14:03 UTC, furtivite approved these changes

2021-09-10 14:05 UTC, igsekor approved these changes

2021-09-11 19:27 UTC, nlopin commented on src/scripts/modules/search.js
> +const MIN_SEARCH_SYMBOLS = 3
Перенёс обсуждение в #299

2021-09-11 19:29 UTC, nlopin commented on src/scripts/modules/search.js
> +function adjustTextMatch(text, index, query, limit) {
@igsekor если будешь делать отдельным пул реквестом, то давай заведём ишью. Опишем, что хотим поправить, зарезолвим здесь все диалоги и смёржим. 

Только нужно не затянуть с рефакторингом, а то потеряем контекст

2021-09-13 11:05 UTC, pepelsbey commented
@monochromer мёржим, готово?

2021-09-13 11:09 UTC, monochromer commented
> @monochromer мёржим, готово?

да

2021-09-13 11:11 UTC, merged