Разделение блоков кода от преформатированного текста
doka-guide/platform pull request #334
Opened 2021-09-09 07:01 UTC by monochromer

Относится к #330

2021-09-09 17:46 UTC, pepelsbey approved these changes

2021-09-09 20:15 UTC, furtivite requested changes
Стоит посмотреть преформатирование в статьте "Работа с формами" ([ссылка на текущий сайт](https://doka.guide/js/deal-with-forms/)), там есть преформатированный текст (начинается на HTMLFormControlsCollection), который не скрывается за край, в `overflow`, а влияет на остальной контент. 

![Снимок экрана 2021-09-09 231158](https://user-images.githubusercontent.com/50330458/132756125-cdbca47c-b542-4e83-a208-cd5c20e9b054.png)

Кажется, этот PR, может решить эту проблему.

2021-09-10 08:24 UTC, igsekor approved these changes

2021-09-10 09:29 UTC, furtivite approved these changes

2021-09-10 09:32 UTC, merged