Добавляет тэг Google Analytics
doka-guide/platform pull request #444
Opened 2021-09-26 14:19 UTC by igsekor

Переместил тэги для Метрики и GA повыше в head-секцию, как рекомендуют сами системы. Предлагаю попробовать так. На основе анализа живых данных поймём, как вариант нам лучше. Здесь два поинта: время загрузки страницы и корректность данных.

2021-09-26 21:59 UTC, nlopin approved these changes

2021-09-26 21:59 UTC, nlopin commented on src/includes/analytics/metrika.njk
> +<noscript><div><img src="https://mc.yandex.ru/watch/83244811" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
Нам точно нужно это изменение?

2021-09-27 05:31 UTC, furtivite approved these changes

2021-09-27 13:31 UTC, pepelsbey requested changes

2021-09-27 13:31 UTC, pepelsbey commented on src/includes/analytics/metrika.njk
> +<noscript><div><img src="https://mc.yandex.ru/watch/83244811" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
```suggestion
<noscript><img src="https://mc.yandex.ru/watch/83244811" style="position:absolute;left:-9999px" alt=""></noscript>
```

2021-09-27 13:31 UTC, pepelsbey commented on src/includes/analytics/google.njk
> +</script>
```suggestion
<script async src="https://www.googletagmanager.com/gtag/js?id=G-GH8FX28ET0"></script>
<script>
  window.dataLayer = window.dataLayer || []
  function gtag(){dataLayer.push(arguments)}
  gtag('js', new Date())
  gtag('config', 'G-GH8FX28ET0')
</script>
```

2021-09-27 14:29 UTC, igsekor commented on src/includes/analytics/metrika.njk
> +<noscript><div><img src="https://mc.yandex.ru/watch/83244811" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
Давайте я проверю. Так красивее. Осталось понять, как это отразиться на работе GA

2021-09-27 14:48 UTC, pepelsbey approved these changes

2021-09-27 14:48 UTC, merged