Добавляет мета-тег theme-color
doka-guide/platform pull request #452
Opened 2021-09-27 19:33 UTC by monochromer

2021-09-27 20:30 UTC, monochromer commented
Похоже, валидатор не поддерживает theme-color

2021-09-27 21:34 UTC, nlopin approved these changes

2021-09-28 05:47 UTC, furtivite requested changes
Нужно поправить в Safari 15:

1. Переключение кнопкой на сайте
    - На главной и сервисных страницах не красятся заголовки
    <img width="1552" alt="Screenshot 2021-09-28 at 08 36 31" src="https://user-images.githubusercontent.com/50330458/135029422-d9520707-50b8-4bdd-8b19-336816082eab.png">
    - В HTML, CSS, JS, TOOLS цвет заголовка отличается от цвета `<header>`
    <img width="1552" alt="Screenshot 2021-09-28 at 08 42 40" src="https://user-images.githubusercontent.com/50330458/135029998-431da6db-d2f8-42fa-87cd-4ba04e1f08e1.png">
1. Включаю системную тёмную тему
    - НTML, JS, TOOLS — не меняет цвет системного заголовка
    <img width="1552" alt="Screenshot 2021-09-28 at 08 38 17" src="https://user-images.githubusercontent.com/50330458/135029574-1c9b255f-57e9-4529-8371-0550d911c361.png">
    - CSS не затемняет цвет браузера, он отличается от цвета блока `<header>`
    <img width="1552" alt="Screenshot 2021-09-28 at 08 39 20" src="https://user-images.githubusercontent.com/50330458/135029704-21ea0600-e88f-4690-bd62-8e73b1512419.png">

2021-09-28 07:41 UTC, pepelsbey commented on src/includes/meta.njk
> +  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000">
Значение `content` нужно всё-таки другие выставить, не? :)

2021-09-28 07:46 UTC, monochromer commented on src/includes/meta.njk
> +  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000">
какие?

2021-09-28 08:22 UTC, pepelsbey commented on src/includes/meta.njk
> +  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000">
Брр, торможу. Сейчас напишу, что имел в виду.

2021-09-28 08:24 UTC, pepelsbey requested changes
Хорошее начало, но принцип должен быть чуть другой:

1. В шапке всегда стоит пара theme-color
2. Значения у них следующие:

Если есть категория:
- Светлая категория
- Тёмная категория

Если нет категории:
- Белый
- Чёрный

2021-09-28 22:29 UTC, pepelsbey approved these changes

2021-09-29 10:20 UTC, furtivite requested changes
Если в системе установлена тёмная тема, а потом кнопкой сменить на светлую в safari останется цвет от тёмной темы. 

<img width="1359" alt="Screenshot 2021-09-29 at 13 16 16" src="https://user-images.githubusercontent.com/50330458/135250217-f3b12df0-621a-4ae6-b59c-747b6e64f741.png">

Если обновить страницу, или вернутсья на главную, а потом в категорию, то встанет системная тёмня тема

<img width="1359" alt="Screenshot 2021-09-29 at 13 17 24" src="https://user-images.githubusercontent.com/50330458/135250280-a7028801-f31c-4f43-8e70-f2ca359ecb92.png">

На главной тоже сохраняется системная тёмная тема. 

Если после этого включить системную светлую тему, на главной останется заголовок от светлой темы:

<img width="1359" alt="Screenshot 2021-09-29 at 13 18 47" src="https://user-images.githubusercontent.com/50330458/135250440-15f7cc79-ad7e-4710-8628-7ef1fbfecfc2.png">

После перехода в категорию тоже сохраняется заголовок от светлой темы:

<img width="1359" alt="Screenshot 2021-09-29 at 13 19 20" src="https://user-images.githubusercontent.com/50330458/135250550-9336aa4d-0ed2-4a48-821e-0e14e93d1a67.png">

2021-10-04 21:06 UTC, pepelsbey commented
В общем, решение такое: механизм этот хрупкий вмешательства в атрибут media не терпит, так что нужно изменить логику:

## Состояние по умолчанию

```html
<meta name="theme-color" media="(prefers-color-scheme: light)" content="DARK">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="LIGHT">
```

Браузер сам выбирает тему.

## Зафорсили светлую тему

```html
<meta name="theme-color" media="(prefers-color-scheme: light)" content="LIGHT">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="LIGHT">
```

Скрипт проставляет мете `prefers-color-scheme: light` значение `LIGHT`.

## Зафорсили тёмную тему

```html
<meta name="theme-color" media="(prefers-color-scheme: light)" content="DARK">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="DARK">
```

Скрипт проставляет мете `prefers-color-scheme: dark` значение `DARK`.

…

Когда выставляется «авто», то значения возвращаются к дефолтным.

2021-10-04 21:07 UTC, pepelsbey commented
@monochromer закодишь реализацию? Раз уж мы взялись за тёмную тему, то хорошо бы доделать.

2021-10-05 06:19 UTC, monochromer commented
> @monochromer закодишь реализацию? Раз уж мы взялись за тёмную тему, то хорошо бы доделать.

Добавил

2021-10-05 06:33 UTC, monochromer commented
Кажется, ещё [и это](https://github.com/doka-guide/platform/issues/412) поправилось.

2021-10-05 07:57 UTC, pepelsbey commented
Завёл #472 насчёт ошибки валидатора

2021-10-05 08:19 UTC, pepelsbey approved these changes
Огонь!

2021-10-05 11:35 UTC, furtivite commented
- Если установлена системная тёмная тема, то в HTML, JS и Инструментах, шапка красится в системную тёмную тему при ручном переключении сайта на светлую. В CSS всё работает отлично:


<img width="1436" alt="Screenshot 2021-10-05 at 14 31 47" src="https://user-images.githubusercontent.com/50330458/136014917-58b3bd48-d802-49b0-84a9-345e78db273f.png">
<img width="1436" alt="Screenshot 2021-10-05 at 14 32 51" src="https://user-images.githubusercontent.com/50330458/136014930-6ffc67ce-8d47-474d-9140-53f34d0375cc.png">

> Кажется, ещё [и это](https://github.com/doka-guide/platform/issues/412) поправилось.

- В Safari 15 — не поправилось, мигание существует. В FF и Chrome — действительно, решает.

2021-10-05 11:36 UTC, furtivite commented
@monochromer, @pepelsbey — это уже большой шаг вперёд, мне кажется, что такое поведение можно вывести в отдельный issue для фикса, а существующее решение залить.

2021-10-05 11:42 UTC, pepelsbey commented
@furtivite тогда апрувни ПР, пожалуйста

2021-10-05 11:49 UTC, pepelsbey commented on config/category-colors.js
> +  },
А почему у тёмных значений есть `25deg`, а у светлых нет `25`?

2021-10-05 11:53 UTC, pepelsbey commented
> Если установлена системная тёмная тема, то в HTML, JS и Инструментах, шапка красится в системную тёмную тему при ручном переключении сайта на светлую. В CSS всё работает отлично:

@furtivite это фича Safari: браузер запрещает красить заголовок браузера в неконтрастные цвета, поскольку в системной теме там белые иконки. Мы с этим ничего не сможем поделать.

2021-10-05 11:54 UTC, monochromer commented on config/category-colors.js
> +  },
Ctrl + C, Ctrl + V из браузера

2021-10-05 11:55 UTC, furtivite approved these changes

2021-10-05 12:12 UTC, merged

2021-10-05 12:13 UTC, pepelsbey commented
Урааа! Спасибо всем :)