Отпиливает всё про Netlify
doka-guide/platform pull request #734
Opened 2021-11-05 10:29 UTC by pepelsbey

Из формы фидбека отпилил только дата-атрибут, чтобы не нервировал :)

2021-11-05 10:55 UTC, igsekor approved these changes

2021-11-05 10:55 UTC, igsekor requested changes

2021-11-05 10:55 UTC, igsekor commented on src/includes/feedback-form.njk
> +<form class="feedback-form" name="{{ constants.feedbackFormName }}" method="post" autocomplete="off" data-state="idle">
```suggestion
<form class="feedback-form" method="post" autocomplete="off" data-state="idle">
```

Забыл я удалить(

2021-11-05 11:03 UTC, igsekor approved these changes

2021-11-05 11:04 UTC, pepelsbey commented
Вернул шильдик

2021-11-05 11:05 UTC, igsekor approved these changes

2021-11-08 06:52 UTC, furtivite approved these changes

2021-11-08 13:13 UTC, tachisis approved these changes

2021-11-08 21:21 UTC, merged