Добавляет метки к ссылке на Практикум
doka-guide/platform pull request #768
Opened 2021-11-17 16:40 UTC by pepelsbey

Чтобы на той стороне лучше понимали, что пришли от нас.

2021-11-17 17:05 UTC, monochromer approved these changes

2021-11-17 19:08 UTC, igsekor commented on src/includes/blocks/footer.njk
> +        <a class="footer-list__link link" href="https://practicum.yandex.ru?utm_source=pr&amp;utm_medium=content&amp;utm_campaign=pr_content_main_doka">При поддержке Яндекс.Практикума</a>
```suggestion
        <a class="footer-list__link link" href="https://practicum.yandex.ru?utm_source=doka-site&utm_medium=content&utm_campaign=pr_content_main_doka&utm_content=link-in-footer">При поддержке Яндекс.Практикума</a>
```

2021-11-17 19:10 UTC, igsekor commented on src/includes/blocks/footer.njk
> +        <a class="footer-list__link link" href="https://practicum.yandex.ru?utm_source=pr&amp;utm_medium=content&amp;utm_campaign=pr_content_main_doka">При поддержке Яндекс.Практикума</a>
Кажется, так более понятно (если у Практикума нет специальных требований):
- источник: doka-site
- тип медиа: content
- кампания: pr_content_main_doka
- детализация: link-in-footer

2021-11-17 19:11 UTC, igsekor requested changes
Кажется, так более понятно (если у Практикума нет специальных требований):
- источник: doka-site
- тип медиа: content
- кампания: pr_content_main_doka
- детализация: link-in-footer

2021-11-17 19:15 UTC, nlopin approved these changes

2021-11-25 12:51 UTC, igsekor requested changes

2021-11-25 12:51 UTC, igsekor commented on src/includes/blocks/footer.njk
> +        <a class="footer-list__link link" href="https://practicum.yandex.ru?utm_source=pr&amp;utm_medium=content&amp;utm_campaign=pr_content_main_doka">При поддержке Яндекс.Практикума</a>
Кажется, нужно заменить `&amp;` на `&`.

2021-11-27 09:36 UTC, pepelsbey commented
В общем, это очень [длинная история](https://mathiasbynens.be/notes/ambiguous-ampersands) с амперсандом.

Главное, что в нашем случае кодировать не нужно.

2021-11-27 09:39 UTC, merged