Фикс ошибки в консоли на страницах /html, /css, /js
doka-guide/platform pull request #793
Opened 2021-12-06 17:06 UTC by devcustrom

2021-12-07 07:28 UTC, monochromer commented on src/scripts/modules/article-aside.js
> +  if (!articleAside) return
Кажется, достаточно поправить здесь

```suggestion
if (!(articleAside && headerComponent)) {
```

2021-12-07 07:28 UTC, monochromer commented on src/scripts/modules/quick-search.js
> +    if(!rootElement) return
Мне не очень нравится такой способ. Он предотвращает дальнейшую инициализацию в методе `constructor`, но, в итоге, из него всё равно возвращается экземпляр класса.

2021-12-07 09:20 UTC, devcustrom commented on src/scripts/modules/article-aside.js
> +  if (!articleAside) return
Ну Я не нашел упоминаний headerComponent в импортируемом файле, но можно и так

2021-12-07 09:21 UTC, devcustrom commented on src/scripts/modules/quick-search.js
> +    if(!rootElement) return
Это обычная проверка, на наличие класса, как вариант можно сделать условие, что если нет rootElement из вне, присваивать rootElement дефолтное значение

2021-12-09 19:03 UTC, igsekor requested changes
Надо бы ошибки сборки поправить 😇

2021-12-10 10:42 UTC, monochromer commented on src/scripts/modules/quick-search.js
> +    if(!rootElement) return
Для решения текущей проблемы это лишнее, поэтому эти изменения нужно откатить.

2021-12-17 16:50 UTC, igsekor approved these changes

2021-12-17 20:20 UTC, merged