Добавляет страницы для людей
doka-guide/platform pull request #807
Opened 2021-12-10 12:36 UTC by monochromer

Fix: #720

2021-12-15 12:23 UTC, pepelsbey commented
Нам ещё нужна индексная страница для /people, как обзор всех, кто участвует в создании Доки.

Сегодня обсудим, будем ли мы заводить страницы для всех-всех people или только для части.

2021-12-16 12:13 UTC, pepelsbey commented
Конвертнул в черновик, поскольку пришли новые вводные от дизайна. Как минимум — индексная страница.

2022-04-05 15:43 UTC, igsekor approved these changes
Есть момент со шрифтом описания на странице автора. Был сделан адаптив для обычного текста. Будем ли мы его применять или делаем по дизайну? У нас там необычные значения...

2022-04-12 07:41 UTC, solarrust commented
Кажется, осталось только убрать вывод даты статьи и можно сливать ♥️

2022-04-12 07:46 UTC, skorobaeus approved these changes

2022-04-12 09:59 UTC, igsekor commented
> Кажется, осталось только убрать вывод даты статьи и можно сливать ♥️

@pepelsbey @solarrust @skorobaeus @nlopin @furtivite @tachisis пришло время смотреть, одобрять и в прод.

Есть момент с хлебными крошками. Везде на сайте Алексей сделал так, что раздел скрывается для мобильных. Так и было по дизайну раньше. Теперь хлебные крошки другие. Я поправлю это автоматически и для раздела «Участники», когда закончу с хлебными крошками. Они в работе у меня сейчас.

2022-04-12 10:36 UTC, furtivite commented
_Возможно это не будет проблемой на рабочем сайте, но оставлю коммент тут на посмотреть всем, кто делает или проверяет._ 

При сборке локально, терминал выдал ошибку:

```bash
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > This endpoint requires you to be authenticated.

`HttpError` was thrown:
[11ty]     HttpError: This endpoint requires you to be authenticated.
        at /Users/furtivite/Developer/doka/platform/node_modules/@octokit/request/dist-node/index.js:86:21
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 0)
        at async getAuthorsContribution (/Users/furtivite/Developer/doka/platform/src/libs/github-contribution-service/github-contribution-service.js:53:39)
```

Ветка не собралась.

2022-04-12 10:38 UTC, igsekor commented
> _Возможно это не будет проблемой на рабочем сайте, но оставлю коммент тут на посмотреть всем, кто делает или проверяет._
> 
> При сборке локально, терминал выдал ошибку:
> 
> ```shell
> [11ty] Problem writing Eleventy templates: (more in DEBUG output)
> [11ty] > This endpoint requires you to be authenticated.
> 
> `HttpError` was thrown:
> [11ty]     HttpError: This endpoint requires you to be authenticated.
>         at /Users/furtivite/Developer/doka/platform/node_modules/@octokit/request/dist-node/index.js:86:21
>         at processTicksAndRejections (node:internal/process/task_queues:96:5)
>         at async Promise.all (index 0)
>         at async getAuthorsContribution (/Users/furtivite/Developer/doka/platform/src/libs/github-contribution-service/github-contribution-service.js:53:39)
> ```
> 
> Ветка не собралась.

А ты переустановил зависимости?

2022-04-12 10:41 UTC, furtivite commented
> А ты переустановил зависимости?

Да, я всегда, если вижу что произошли изменения в `package.json`, переустанавливаю.

2022-04-12 10:46 UTC, igsekor commented
> > А ты переустановил зависимости?
> 
> Да, я всегда, если вижу что произошли изменения в `package.json`, переустанавливаю.

Я понял... Надо добавить свой GITHUB_TOKEN (его нужно сгенерировать у себя в профиле)

2022-04-12 10:48 UTC, furtivite commented
> Я понял... Надо добавить свой GITHUB_TOKEN (его нужно сгенерировать у себя в профиле)

Вот тоже только что до этого дошёл (в `.env`)! Спасибо. 

Если будем дальше натыкаться на такую же проблему, то надо бы в инструкцию добавить.

2022-04-12 10:51 UTC, igsekor commented
> > Я понял... Надо добавить свой GITHUB_TOKEN (его нужно сгенерировать у себя в профиле)
> 
> Вот тоже только что до этого дошёл (в `.env`)! Спасибо.
> 
> Если будем дальше натыкаться на такую же проблему, то надо бы в инструкцию добавить.

Мы это уже обсудили на созвоне. Обязательно добавим. Думаю, даже вариант без сборки страниц участников предусмотреть (только там и нужен токен при локальной сборке).

2022-04-12 11:25 UTC, furtivite approved these changes
<img width="1309" alt="Screenshot 2022-04-12 at 14 09 15" src="https://user-images.githubusercontent.com/50330458/162949898-443ac8b3-b7b6-43c2-a412-94c5592a4971.png">

Кажется, всё ок.

2022-04-12 15:21 UTC, tachisis approved these changes
Выглядит отлично

2022-04-13 10:24 UTC, pepelsbey commented
Попробовал поднять локально, получил ошибку после `npm start`:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > This endpoint requires you to be authenticated.

`HttpError` was thrown:
[11ty]     HttpError: This endpoint requires you to be authenticated.
        at /Users/pepelsbey/Documents/Дока/platform/node_modules/@octokit/request/dist-node/index.js:86:21
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 1)
        at async getAuthorsContribution (/Users/pepelsbey/Documents/Дока/platform/src/libs/github-contribution-service/github-contribution-service.js:53:39)
[11ty] Copied 1236 files / Wrote 0 files in 1.91 seconds (v1.0.0)
```

Ошибка не возникает, если переключиться на ветку `main`.

2022-04-13 10:29 UTC, pepelsbey commented
Теперь вижу, что аналогичная ошибка была у Егора выше. Но тут появляется вопрос, смогут ли желающие поднять у себя платформу локально так же легко, как это было до сих пор? Я бы всё же добавил в ридми про токен до мёржа, иначе платформа фактически сломана для всех желающих её поднять.

2022-04-14 09:11 UTC, igsekor commented
> Теперь вижу, что аналогичная ошибка была у Егора выше. Но тут появляется вопрос, смогут ли желающие поднять у себя платформу локально так же легко, как это было до сих пор? Я бы всё же добавил в ридми про токен до мёржа, иначе платформа фактически сломана для всех желающих её поднять.

Сделал так, что при отсутствии `GITHUB_TOKEN ` всё равно собирается сайт с участниками, только без информации об активности на GitHub.

> Я вот пока не знаю, где взять GITHUB_TOKEN в профиле (

Добавил документацию. Надо бы проверить или сформулировать получше...

2022-04-14 15:12 UTC, pepelsbey requested changes
Не уверен, это эффект стики-футера на всём сайте или особенность этой страницы, но контент при высоком окне браузера должен оставаться прижатым к верху, а не центрироваться вертикально.

![Screenshot 2022-04-14 at 17-10-04 Julielesss — Дока](https://user-images.githubusercontent.com/105274/163419837-e0e085a7-b5b4-4f58-a6d7-c282bcd6e67a.png)

![Screenshot 2022-04-14 at 17-10-12 Julielesss — Дока](https://user-images.githubusercontent.com/105274/163419855-acefcd5b-9457-4f81-b9c4-656bdef6c287.png)

2022-05-06 09:27 UTC, nlopin commented
А мы не хотим авторство поставить выше, чем контрибьюторство? Или сортировка сейчас по количеству статей?

2022-05-06 14:45 UTC, igsekor commented
> Согласна, давайте авторство поднимем повыше, в начало

Пробуйте, смотрите 😇

2022-05-07 11:23 UTC, nlopin approved these changes

2022-05-08 10:33 UTC, solarrust approved these changes

2022-05-09 21:27 UTC, pepelsbey approved these changes
:shipit:

2022-05-10 06:09 UTC, merged