Правки manifest.json и добавил maskable иконку
doka-guide/platform pull request #811
Opened 2021-12-13 16:16 UTC by devcustrom

2021-12-15 11:29 UTC, pepelsbey requested changes
Спасибо за новую иконку! К сожалению, Дока пока не готова к тому, чтобы запускаться в режиме standalone. Например, из такого режима не пошарить статью — все кнопки останутся в браузере. В общем, Дока — это пока не веб-приложение в этом смысле.

2021-12-15 11:29 UTC, pepelsbey commented on src/manifest.json
> +  "display": "standalone",
```suggestion
  "display": "browser",
```

2021-12-15 12:17 UTC, pepelsbey commented on src/manifest.json
> +  "display": "standalone",
Насчёт значения «browser» — [оно из спеки](https://w3c.github.io/manifest/#dfn-display-mode). Если вдруг валидатор на него ругается, его можно просто убрать, это всё равно значение по умолчанию.

2021-12-16 13:57 UTC, devcustrom commented on src/manifest.json
> +  "display": "standalone",
Предлагаю использовать тогда `minimal-ui`

2021-12-16 14:29 UTC, pepelsbey commented on src/manifest.json
> +  "display": "standalone",
Мне кажется, что вы неправильно понимаете суть предупреждений: значений `"browser"` корректное.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/105274/146389396-1dfd9af0-f6b8-427c-b24d-f071cb1059ab.png">

Однако с этим значением (а также без сервис-воркера) браузер не будет предлагать установить приложение на домашний экран. Дока — это не приложение (пока), которое нужно устанавливать, Дока — это сайт. Его всё равно можно добавить на домашний экран, если хочется.

Пока манифест играет очень простую роль. Он говорит, что Дока — это сайт для браузера и перечислят иконки. Когда мы дойдём до этапа, когда будем готовы сделать из Доки устанавливаемое приложение — поменяем значение.

2021-12-16 14:30 UTC, pepelsbey approved these changes

2021-12-16 19:56 UTC, devcustrom commented
> Спасибо за новую иконку! К сожалению, Дока пока не готова к тому, чтобы запускаться в режиме standalone. Например, из такого режима не пошарить статью — все кнопки останутся в браузере. В общем, Дока — это пока не веб-приложение в этом смысле.

Может тогда отказаться от строки `browser` раз это по стандарту?

2021-12-17 11:12 UTC, pepelsbey commented
> Может тогда отказаться от строки `browser` раз это по стандарту?

Значение `browser` явно указывает, что мы не забыли это поле, а считаем именно такой режим правильным.

2021-12-17 11:15 UTC, merged

2021-12-17 11:15 UTC, pepelsbey commented
Спасибо!