Добавляет ссылки на смежные статьи
doka-guide/platform pull request #833
Opened 2021-12-20 13:50 UTC by monochromer

Fix: #753

2022-01-19 08:59 UTC, furtivite commented
Привет, выглядит классно, но когда я решил прослистать несколько страниц, и начал кликать `option` + `→`, то страницы не переключаются. `option` надо отпускать перед следующим пролистыванием. Кажется, это может сконфузить пользователя.

2022-01-19 09:00 UTC, furtivite commented
Скорее всего, это не было предусмотрено в дизайне, но может стоит подумать, чтобы вместо `alt` писать `alt ⌥`

2022-01-19 10:08 UTC, monochromer commented
> Привет, выглядит классно, но когда я решил прослистать несколько страниц, и начал кликать `option` + `→`, то страницы не переключаются. `option` надо отпускать перед следующим пролистыванием. Кажется, это может сконфузить пользователя.

Сделал учёт зажатой `Alt`

2022-01-19 11:12 UTC, furtivite commented
> > когда я решил прослистать несколько страниц, и начал кликать `option` + `→`, то страницы не переключаются. `option` надо отпускать перед следующим пролистыванием.
> 
> Сделал учёт зажатой `Alt`

С учётом зажатой `alt` всё работает. Круто.

2022-01-19 11:12 UTC, furtivite commented
Второй вопрос в обсуждению, после небольшого опыта использования, а не хотим ли мы как-то показывать пользователю, что сейчас что-то произойдёт. Потому что страница меняется с небольшой задержкой.

2022-01-30 19:48 UTC, nlopin commented
Блоки рекомендаций без картинок выглядят очень пустыми. У нас такой дизайн?

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/1469636/151715042-87f6fe88-7acb-4fc8-ab50-491a9b80b383.png">

С картинкой тоже блок кажется слишком вытянутым 
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1469636/151715112-55133389-1d8c-449b-bfa8-50a2a72aabb0.png">

2022-01-31 05:51 UTC, monochromer commented
> а не хотим ли мы как-то показывать пользователю, что сейчас что-то произойдёт. Потому что страница меняется с небольшой задержкой.

Это делает браузер, добавляя свои индикаторы загрузки

2022-01-31 06:10 UTC, monochromer commented
> Блоки рекомендаций без картинок выглядят очень пустыми. У нас такой дизайн?

В дизайне не учитывались случаи одновременного отсутствия описания и картинки.

2022-02-05 17:40 UTC, igsekor requested changes
Есть ещё момент, когда мы прижимаем статью из пункта «Остальные», смежные статьи не показываются. Более того, в последней статье предшествующего пункта, смежной статьёй справа будет статья из следующего раздела.

2022-02-07 06:06 UTC, monochromer commented
> Более того, в последней статье предшествующего пункта, смежной статьёй справа будет статья из следующего раздела.

А как должно быть?

2022-02-09 11:30 UTC, igsekor approved these changes
Вот теперь всё правильно! Жаль, что я не успел ответить, но ты абсолютно правильно меня понял.

2022-02-11 11:58 UTC, monochromer commented
Изменил оформление ссылок на малых экранах (< 768px). Сделал выравнивание текста по левому краю, так как вблизи контрольной точки с малым количеством текста всё это выглядит не очень.

2022-02-20 11:35 UTC, igsekor approved these changes

2022-02-25 09:23 UTC, nlopin approved these changes

2022-02-25 09:30 UTC, furtivite approved these changes

2022-03-01 15:22 UTC, pepelsbey approved these changes

2022-03-01 15:22 UTC, merged