Правит документацию по сборке проекта
doka-guide/platform pull request #913
Opened 2022-03-14 10:31 UTC by furtivite

1. После мёржа #882 платформа при сборке автоматически вызывает скрипт и просит указать место, где лежит контент. Поэтому пункт про скрипт больше не нужен. 
    Вот тут можно было бы сократить инструкцию и убрать про «минимальный запуск» и запуск с контентом, а для контента добавить пояснение. Например:
    
    > Чтобы запустить Доку локально, нужно:
    >
    > 1. Скачать репозиторий [c платформой](https://github.com/doka-guide/platform) и [контентом](https://github.com/doka-guide/content) (при необходимости).
    > 1. Установить зависимости командой `npm i`.
    > 1. Сделать копию файла `.env.example` в `.env`. Задать нужные переменные окружения.
    > 1. Запустить локальный веб-сервер командой `npm start`.

1. В #882 добавился пункт про необходимость делать копию переменных окружения. 
    Вот тут есть вопрос больше к @igsekor, насколько обязателен этот пункт, потому что и без создания `.env`-файла с копией `.env.example` всё работает. По крайней мере на macOS.

2022-03-14 12:17 UTC, pepelsbey requested changes

2022-03-14 12:17 UTC, pepelsbey commented on docs/how-to-run.md
> +1. Сделать копию файла `.env.example` в `.env`. Задать нужные переменные окружения.
```suggestion
1. Сделать копию файла `.env.example` и назвать его `.env`. Задать в нём нужные переменные окружения.
```

2022-03-14 12:17 UTC, pepelsbey commented on docs/how-to-run.md
> +1. Сделать копию файла `.env.example` в `.env`. Задать нужные переменные окружения.
```suggestion
1. Сделать копию файла `.env.example` и назвать его `.env`. Задать в нём нужные переменные окружения.
```

2022-03-14 12:46 UTC, furtivite commented on docs/how-to-run.md
> +1. Сделать копию файла `.env.example` в `.env`. Задать нужные переменные окружения.
Я сейчас хотел бы дождаться Игоря, чтобы понять, насколько этот пункт вообще обязателен. И если он обязателен, то тогда сразу поменяю и в главном README отдельным коммитом. Пока тут копипаста оттуда.

2022-03-23 11:23 UTC, tachisis commented
Какие тут у нас новости?

2022-03-23 14:55 UTC, igsekor commented on docs/how-to-run.md
> +1. Сделать копию файла `.env.example` в `.env`. Задать нужные переменные окружения.
Нужно добавить эти строки

2022-03-23 14:56 UTC, igsekor approved these changes
Все замечания нужно добавить в описание, ибо кроме сборки есть сервисные функции, которые без `.env` не заработают.

2022-03-28 07:30 UTC, tachisis approved these changes

2022-03-28 21:16 UTC, pepelsbey approved these changes

2022-03-28 21:17 UTC, merged