Делает шаринг Доки работающим, правит размер шаринг-картинок Twitter-варианта
doka-guide/platform pull request #921
Opened 2022-03-31 20:44 UTC by sglazov

## Что происходит

Самый важный пункт — удалён дубль в `src/includes/meta.njk`.

```diff
- <meta property="twitter:card" content="summary">
```

Ну и правит картинки для twitter-варианта. Они ж квадратно-гигантские: https://doka.guide/js/deal-with-forms/images/covers/twitter.png

В среднем за часа 72 соцсети сами обновляют кэш для шаринга. Если нечто, что нужно обновить — популярно, 
Но частные случаи нужно будет разруливать руками.

## Где и как чистить кэш

* FB: https://developers.facebook.com/tools/debug/
* Twitter: https://cards-dev.twitter.com/validator
* VK: https://vk.com/dev/pages.clearCache
* Tlgrm: https://t.me/WebpageBot 

## Организационное
Открытых ишью про это не нашёл, с чем линковать — не представлю.
И не поставил приставку `fix-` для имени ветки. Сорян.

2022-04-06 12:07 UTC, igsekor requested changes
Кажется, идея хорошая. Давайте тогда уберём всё и исправим ссылки в шаблонах. Как Вам такая идея, @sglazov?

2022-04-06 12:07 UTC, igsekor commented on gulpfile.js
> -            height: 1024,
Если делать один размер карточек для FB и Twitter, проще удалить код в строчках 145—160. Также нужно поправить соответствующий код в шаблонах. Как временное решение подойдёт, сейчас мы в процессе разработки дизайна картинок для соц. сетей.

2022-04-08 10:51 UTC, pepelsbey commented
Спасибо за желание помочь :) На этом и работает Доке. Но учитывая, что нет ишью, хотелось бы в начале ПР подробное объяснение, что именно он исправляет/улучшает и почему это важно. Окей, удаляет дубль. А дальше всё в тумане.

2022-05-27 09:51 UTC, nlopin commented
Привет! У нас началась фаза дизайна всяких штук для соцсетей. Мы будем переделывать шаринг, поэтому я закрою этот пул реквест.

Большое спасибо за инициативу, мы это очень ценим. Будем рады увидеть снова пул реквесты от тебя

2022-05-27 09:51 UTC, closed without merging