Добавляет советы в список материалов участника
doka-guide/platform pull request #949
Opened 2022-07-01 21:41 UTC by igsekor

Возникла необходимость добавить список материалов, для которых участник написал совет. Задача решена.

2022-07-02 22:20 UTC, solarrust reviewed
Если у автора есть только советы, то, почему-то, их не видно на странице.
Можно проверять у авторов `andzhr` и `avebeatrix`.

2022-07-03 10:34 UTC, nlopin commented on config/constants.js
> +  CONTENT_PERSON_ROLES: 'Автор, Контрибьютор, Редактор, Иллюстратор, Автор совета',
безотносительно этого PR: почему мы дублируем, когда можно получить значения из `.env` → `process.env.CONTENT_PERSON_ROLES` ?

думаю стоит создать задачу на устранение дублирования тут

2022-07-03 10:35 UTC, nlopin commented on src/views/person.11tydata.js
> +      return contentPersonRoles[4]
магические числа не круто, тем более, что они читаются из `.env`, который легко изменить. Давай подумаем, как ещё можно доставать эту роль?

2022-07-03 10:40 UTC, nlopin commented on src/views/views.11tydata.js
> +          collections[category].filter((article) => {
Тут можно использовать [`.find()`](doka.guide/js/array-find/), чтобы находить первую статью попавшую под условия

2022-07-03 10:40 UTC, nlopin commented on src/views/views.11tydata.js
> +          })[0]
```suggestion
          collections[category].find((article) => 
            article.filePathStem === `/${category}/${articleId}/index`
          )
```

2022-07-03 10:42 UTC, nlopin commented on src/views/views.11tydata.js
> +          collections[category].filter((article) => {
Сейчас тут есть риск запушить `undefined`, если ничего не нашлось. Не знаю, насколько это критично

2022-07-03 10:45 UTC, nlopin commented on config/constants.js
> +  CONTENT_PERSON_ROLES: 'Автор, Контрибьютор, Редактор, Иллюстратор, Автор совета',
После чтения этого PR я не очень понимаю, зачем нам хранить роли в виде переменной окружения. По сути, мы ожидаем конкретных значений на конкретных позициях в этом списке. Значит, мы не можем произвольно изменить значение переменной и ожидать, что всё продолжит работать как есть.

Предлагаю убрать эти значения из переменных окружения и захардкодить как есть. Можно либо из этого файла экспортировать конкретные значения, а можно прям в код зафигачить

2022-07-03 10:46 UTC, nlopin requested changes
Помимо комментария Алёны, нужно решить с переменными окружения

2022-07-03 17:42 UTC, igsekor commented
> Если у автора есть только советы, то, почему-то, их не видно на странице. Можно проверять у авторов `andzhr` и `avebeatrix`.
> 
> Их, кстати, нет даже на странице участников.

Сделал

2022-07-03 18:04 UTC, pepelsbey approved these changes
LGTM!

2022-07-03 18:18 UTC, pepelsbey approved these changes

2022-07-03 19:13 UTC, skorobaeus approved these changes

2022-07-03 19:23 UTC, furtivite commented
В актуальной версии у меня:

1. Пропала группировка по типу принесённого добра:
    Было
   <img width="1508" alt="Screenshot 2022-07-03 at 22 21 50" src="https://user-images.githubusercontent.com/50330458/177054330-61163c88-a3d7-4ec4-8f74-cd0c548e0a60.png">
    Стало
   <img width="1508" alt="Screenshot 2022-07-03 at 22 21 13" src="https://user-images.githubusercontent.com/50330458/177054342-c0e5a0b7-641f-42f5-b182-56f88cc850c7.png">
   
2. Пропали контрибьюшны, которые не про совет.

2022-07-03 22:50 UTC, igsekor commented
> В актуальной версии у меня:
> 1. Пропала группировка по типу принесённого добра:
> 2. Пропали контрибьюшны, которые не про совет.

Починил вроде 🙃

2022-07-04 05:39 UTC, furtivite approved these changes
Советы отображаются группой. 
Советы не замещают авторский и контрибуторский вклад. 
Кажется, пора мёржить.

На странице людей аватарки стали либо фото, либо серые. Цвета пропали. Это не критично и можно поправить в следующей итерации, как мне кажется.

2022-07-04 05:59 UTC, solarrust commented
По всей видимости аватарки обесцветились из-за `mostContributedCategory`. Но найти как это починить у меня не получилось =(
Можем и правда вернуться к этому отдельно!

2022-07-04 05:59 UTC, solarrust approved these changes

2022-07-04 06:07 UTC, nlopin commented on .env.example
> +CONTENT_PERSON_ROLES="Автор, Контрибьютор, Редактор, Иллюстратор, Автор совета"
Кажется надо дропнуть эту строку
```suggestion
```

2022-07-04 06:18 UTC, nlopin commented
Запустил локально — показываются все цвета у аватарок 🤷‍♂️

2022-07-04 06:18 UTC, nlopin approved these changes

2022-07-04 11:09 UTC, merged