Добавляет поддержку ссылок на Telegram для страницы автора
doka-guide/platform pull request #995
Opened 2022-10-08 17:31 UTC by denisputnov

Добавляет поддержку ссылок в формате `https://www.t.me/username`

Пример:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58640700/194720127-d024a35d-3f06-4d70-8e85-1478ce89c0a1.png">

2022-10-09 12:37 UTC, igsekor requested changes
Да вроде ничего получилось.

2022-10-09 12:37 UTC, igsekor commented on src/views/person.njk
> +</svg>
```suggestion
<svg class="person-links-list__icon" width="11" height="11" viewBox="0 0 11 11" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.5 0.083333C4.06341 0.083333 2.68566 0.654016 1.66984 1.66984C0.654016 2.68566 0.083333 4.06341 0.083333 5.5C0.083333 6.93659 0.654016 8.31434 1.66984 9.33016C2.68566 10.346 4.06341 10.9167 5.5 10.9167C6.93659 10.9167 8.31434 10.346 9.33016 9.33016C10.346 8.31434 10.9167 6.93659 10.9167 5.5C10.9167 4.06341 10.346 2.68566 9.33016 1.66984C8.31434 0.654016 6.93659 0.083333 5.5 0.083333V0.083333Z" fill="#29B6F6"/>
  <path d="M8.19479 3.0625L7.18025 8.24246C7.18025 8.24246 7.13665 8.47917 6.84306 8.47917C6.68706 8.47917 6.60662 8.40496 6.60662 8.40496L4.40908 6.58144L3.33387 6.0395L1.95398 5.67252C1.95398 5.67252 1.70833 5.60156 1.70833 5.39844C1.70833 5.22917 1.96102 5.14846 1.96102 5.14846L7.7341 2.85504C7.73383 2.85477 7.91042 2.7914 8.03906 2.79167C8.11815 2.79167 8.20833 2.82552 8.20833 2.92708C8.20833 2.99479 8.19479 3.0625 8.19479 3.0625Z" fill="#FFFFFF"/>
  <path d="M5.22917 7.26177L4.30129 8.17556C4.30129 8.17556 4.26094 8.20671 4.20704 8.20806C4.18835 8.2086 4.16831 8.20563 4.14773 8.19642L4.40881 6.5809L5.22917 7.26177Z" fill="#B0BEC5"/>
  <path d="M7.0971 3.92808C7.05133 3.8685 6.96683 3.85767 6.90725 3.9029L3.33333 6.04167C3.33333 6.04167 3.90371 7.63742 3.99065 7.91367C4.07785 8.19019 4.14773 8.19669 4.14773 8.19669L4.40881 6.58117L7.07165 4.11767C7.13123 4.07244 7.14233 3.98767 7.0971 3.92808Z" fill="#CFD8DC"/>
</svg>
```

Чуть подредактировал иконку.

2022-10-09 13:00 UTC, StarHamster commented on src/views/person.njk
> +</svg>
```suggestion
<svg class="person-links-list__icon" width="11" height="11" viewBox="0 0 1000 1000">
  <defs>
    <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="Gradient">
      <stop stop-color="#2AABEE" offset="0%"></stop>
      <stop stop-color="#229ED9" offset="100%"></stop>
    </linearGradient>
  </defs>
  <g>
    <circle fill="url(#Gradient)" cx="500" cy="500" r="500"></circle>
    <path fill="#FFF" d="M226.328419,494.722069 C372.088573,431.216685 469.284839,389.350049 517.917216,369.122161 C656.772535,311.36743 685.625481,301.334815 704.431427,301.003532 C708.567621,300.93067 717.815839,301.955743 723.806446,306.816707 C728.864797,310.92121 730.256552,316.46581 730.922551,320.357329 C731.588551,324.248848 732.417879,333.113828 731.758626,340.040666 C724.234007,419.102486 691.675104,610.964674 675.110982,699.515267 C668.10208,736.984342 654.301336,749.547532 640.940618,750.777006 C611.904684,753.448938 589.856115,731.588035 561.733393,713.153237 C517.726886,684.306416 492.866009,666.349181 450.150074,638.200013 C400.78442,605.66878 432.786119,587.789048 460.919462,558.568563 C468.282091,550.921423 596.21508,434.556479 598.691227,424.000355 C599.00091,422.680135 599.288312,417.758981 596.36474,415.160431 C593.441168,412.561881 589.126229,413.450484 586.012448,414.157198 C581.598758,415.158943 511.297793,461.625274 375.109553,553.556189 C355.154858,567.258623 337.080515,573.934908 320.886524,573.585046 C303.033948,573.199351 268.692754,563.490928 243.163606,555.192408 C211.851067,545.013936 186.964484,539.632504 189.131547,522.346309 C190.260287,513.342589 202.659244,504.134509 226.328419,494.722069 Z"></path>
  </g>
</svg>
```

Поменял логотип на новый и поджал его ручками, как только смог. viewBox только осталось заскейлить, но никаких сервисов для этого не нашел. Мб, мейнтейнеры придут и помогут 🤞

2022-10-09 13:02 UTC, StarHamster commented on src/views/person.njk
> +</svg>
Это старое лого. Не стоит его использовать

2022-10-11 16:35 UTC, igsekor commented on src/views/person.njk
> +</svg>
Да, действительно. Сделал новый саджест с правильным лого.

2022-10-11 16:35 UTC, igsekor commented on src/views/person.njk
> +</svg>
Так делать тоже неправильно. Сделал новый саджест.

2022-10-11 16:36 UTC, igsekor commented on src/views/person.njk
> +</svg>
```suggestion
<svg class="person-links-list__icon" width="11" height="11" viewBox="0 0 11 11" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.5 11C8.53757 11 11 8.53757 11 5.5C11 2.46243 8.53757 0 5.5 0C2.46243 0 0 2.46243 0 5.5C0 8.53757 2.46243 11 5.5 11Z" fill="#2AABEE"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M2.48961 5.44194C4.09297 4.74338 5.16213 4.28285 5.69709 4.06034C7.2245 3.42504 7.54188 3.31468 7.74875 3.31104C7.79424 3.31024 7.89597 3.32151 7.96187 3.37498C8.01751 3.42013 8.03282 3.48112 8.04015 3.52393C8.04747 3.56674 8.0566 3.66425 8.04935 3.74045C7.96657 4.61013 7.60843 6.72061 7.42622 7.69467C7.34912 8.10683 7.19732 8.24502 7.05035 8.25855C6.73095 8.28794 6.48842 8.04747 6.17907 7.84469C5.695 7.52737 5.42153 7.32984 4.95165 7.0202C4.40863 6.66236 4.76065 6.46568 5.07011 6.14425C5.1511 6.06014 6.55837 4.78012 6.5856 4.664C6.58901 4.64948 6.59217 4.59535 6.56001 4.56676C6.52785 4.53818 6.48039 4.54796 6.44614 4.55573C6.39759 4.56675 5.62428 5.07788 4.12621 6.08912C3.9067 6.23985 3.70789 6.31328 3.52975 6.30944C3.33337 6.30519 2.95562 6.1984 2.6748 6.10712C2.33036 5.99515 2.05661 5.93596 2.08045 5.74581C2.09286 5.64677 2.22925 5.54548 2.48961 5.44194Z" fill="#FFF"/>
</svg>
```

2022-10-11 16:42 UTC, StarHamster commented on src/views/person.njk
> +</svg>
А что конкретно не так? Буду рад, если смогу в следующий раз сделать сразу правильно)

2022-10-11 16:48 UTC, igsekor commented on src/views/person.njk
> +</svg>
У Вас не совпадает размер картинки и размер вьюпорта. Привязка идёт внутренних элементов тоже к большим размерам. Из-за этого в некоторых браузерах плывёт привязка. Важно все элементы масштабировать сразу. А ещё градиент тут вряд ли уместен, поскольку картинка очень маленькая. Зачем занимать лишние символы. Ну и закрывающий тег у `<circle>` не нужен.

2022-10-11 16:58 UTC, StarHamster commented on src/views/person.njk
> +</svg>
Окей, спасибо. А каким инструментом вьюпорт скейлить?..

2022-10-11 17:09 UTC, igsekor commented on src/views/person.njk
> +</svg>
Да можно почти в любом редакторе. Например, Figma, Sketch или Adobe Illustrator. Я делал в Figma на этот раз, но нужно смотреть на `path`. Figma очень любит заменять им `circle`.

2022-10-13 10:24 UTC, igsekor approved these changes

2022-10-13 17:19 UTC, merged