Правит переносы имён методов
doka-guide/platform pull request #998
Opened 2022-10-11 09:18 UTC by Inventoris

Fix #992

Сделал так, чтобы переносы не ставились для первых спецсимволов в коде. 

Было:

![image](https://user-images.githubusercontent.com/106589280/195050066-6248766d-3b5d-42dd-b88b-459bed29c4dc.png)

Стало:

![image](https://user-images.githubusercontent.com/106589280/195050120-18a44c06-74a8-4273-a2be-b20111f95610.png)

Также добавил тройку комментов по коду, чтобы другим было легче разобраться 🙂

2022-10-11 17:00 UTC, igsekor requested changes
Да можно и так :)

2022-10-11 17:00 UTC, igsekor commented on src/transforms/code-breakify-transform.js
> +      content = content.replaceAll(symbol, `<wbr>${symbol}<wbr>`).replace(firstSymbolWithinTags, `${symbol}`)
```suggestion
    const firstSymbolWithinTags = new RegExp(`^(<wbr>)[\\${symbol}](<wbr>)`, '')

    content = content.replaceAll(symbol, `<wbr>${symbol}<wbr>`)

    // Исключение для переносов первого спецсимвола в слове
    if (startsWithSymbol.test(content)) {
      content = content.replace(firstSymbolWithinTags, `${symbol}`)
```

Кажется, так лаконичнее.

2022-10-11 18:48 UTC, Inventoris commented on src/transforms/code-breakify-transform.js
> +      content = content.replaceAll(symbol, `<wbr>${symbol}<wbr>`).replace(firstSymbolWithinTags, `${symbol}`)
Да, выглядит лаконичнее! Но проблема в том, что если сперва мы размечаем `content`, а уже потом вводим исключение, то имена методов будут начинаться с конструкции `<wbr>`, а не со спецсимвола, поэтому `startsWithSymbol` будет всё время `false`, и исключение не сработает.

По этой причине я размечал `content` после проверки, чтобы этот регэксп работал.

Но можно и правда сильно сократить, не потеряв смысл. Щас подумал, а как на счёт просто махнуть `startsWithSymbol` на `firstSymbolWithinTags` в исключении? Тогда и лаконичнее станет, и всё заработает, и кода меньше! 😀

2022-10-11 18:49 UTC, igsekor commented on src/transforms/code-breakify-transform.js
> +      content = content.replaceAll(symbol, `<wbr>${symbol}<wbr>`).replace(firstSymbolWithinTags, `${symbol}`)
Давайте пробовать уже! 🚀

2022-10-11 18:57 UTC, igsekor approved these changes
Ну вроде взлетает)

2022-10-13 09:41 UTC, nlopin approved these changes

2022-10-13 09:42 UTC, merged